(* Each new term in the Fibonacci sequence is generated by adding the
   previous two terms. By starting with 1 and 2, the first 10 terms
   will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

   By considering the terms in the Fibonacci sequence whose values do
   not exceed four million, find the sum of the even-valued terms. *)

let fib_limit = 4000000;;

(* This is pretty much the simplest fibonacci function. It is
   inefficient: to calculate the 30th fibonacci number requires over 2
   million function calls.  Oh no!*)

let rec fib n =
  match n with
    0 -> 1
  | 1 -> 2
  | _ -> fib (n - 1) + fib (n - 2);;

(* This is a more efficient O(n), tail recursive fibonacci function.
   However, this optimisation was pointless.  The naive fibonacci
   function is easily fast enough for our needs. *)
let fib n =
  let first_fib = 1 and second_fib = 2
  in
  let rec aux n' acc1 acc2 =
    match n with
      0 -> first_fib
    | 1 -> second_fib
    | _ -> if n' = n
           then acc1 + acc2
           else aux (n' + 1) acc2 (acc1 + acc2)
  in aux 2 first_fib second_fib;;

let fib_upto x =
  let rec aux n =
    let f = fib n in
    if f > x
    then []
    else f :: aux (n + 1)
  in aux 0;;

let evens = List.filter (fun x -> x mod 2 = 0) (fib_upto fib_limit);;

let sum_of_evens = List.fold_left (fun x y -> x + y) 0 evens;;
